---
apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: CuratedAPIDescriptor
metadata:
  name: petstore
  namespace: test-e2e-curation
  annotations:
    "apis.apps.tanzu.vmware.com/route-provider": "spring-cloud-gateway"
spec:
  title: Curated Petstore
  description: A set of API endpoints to manage the resources within the petstore app.
  documentation:
    url: https://docs.example.com
  type: openapi
  groupId: profile-management
  version: 1.2.3
  apiDescriptors:
    - name: customer-profile
      namespace: my-apps
      pathPrefix: /customers
      routeConfig:
        ssoEnabled: true
        filters: ["TokenRelay", "RateLimit=2,10s"]
    - name: employee-profile
      namespace: my-apps
      pathPrefix: /employees
    - name: pet-profile
      namespace: default
      pathPrefix: /pets

---
apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: pet-profile
  namespace: default
spec:
  type: openapi
  location:
    apiSpec:
      path: "/api/v3/openapi.json"
    server:
      url: https://petstore3.swagger.io
