apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: profile-management
  namespace: gateway
spec:
  sso:
    secret: external-users-sso
  api:
    title: Profile Management
    description: All the profiles in one place!
    version: 1.2.3
    groupId: profile-management
    serverUrl: http://profile-management.tap.test-api-curation.tapdemo.vmware.com
    cors:
      allowedOrigins:
        - "http://localhost:4333"
        - "http://tap-gui.tap.test-api-curation.tapdemo.vmware.com"
        - "http://api-portal.tap.test-api-curation.tapdemo.vmware.com"
      allowedMethods:
        - "GET"
        - "PUT"
        - "POST"
      allowedHeaders:
        - '*'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-management
  namespace: gateway
spec:
  ingressClassName: contour
  rules:
    - host: profile-management.tap.test-api-curation.tapdemo.vmware.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profile-management
                port:
                  number: 80
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: external-users-sso
  namespace: gateway
spec:
  authServerSelector:
    matchLabels:
      name: my-auth-server
  clientAuthenticationMethod: client_secret_basic
  requireUserConsent: false
  authorizationGrantTypes:
    - authorization_code
  redirectURIs:
    - http://127.0.0.1:8080
    - http://127.0.0.1:8080/
    - http://127.0.0.1
    - http://127.0.0.1:80
    - http://127.0.0.1:80/
    - http://127.0.0.1:80/login/oauth2/code/sso
    - http://profile-management.tap.test-api-curation.tapdemo.vmware.com
    - http://profile-management.tap.test-api-curation.tapdemo.vmware.com/login/oauth2/code/sso
    - https://oauth.pstmn.io/v1/callback  #! https://learning.postman.com/docs/sending-requests/authorization/#oauth-20
  scopes:
    - name: openid
    - name: profile
    - name: roles
    - name: email