---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: my-token-signing-key
  namespace: appsso
spec: { }
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: my-token-verification-key
  namespace: appsso
spec: { }

---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: my-auth-server
  namespace: appsso
  labels:
    name: my-auth-server
  annotations:
    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: "true"
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: "true"
    sso.apps.tanzu.vmware.com/allow-client-namespaces: "*"
spec:
  replicas: 1
  tls:
    deactivated: true
  identityProviders:
    - name: internal
      internalUnsafe:
        users:
          - username: "alice"
            password: "{bcrypt}$2a$10$FKC5icCWPYwuzvYVyzxkt.W.0FTlP3lqzsR5m9ijJaxKfxJR8ff7q" #! "test"
            claims:
              givenName: "alice"
              familyName: "scg"
            roles:
              - "openid"
              - "profile"
  tokenSignature:
    signAndVerifyKeyRef:
      name: my-token-signing-key
    extraVerifyKeyRefs:
      - name: my-token-verification-key


